### ISSUE TITLE
GCaccount registration - A11y issues with password requirements

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/concierge#222]
The password requirements on GCAccount registration do not appear to get picked up by assistive technology. There are also issues with the hover / onclick icon in the password label. Rethink an accessible way to display the password requirements.

![Image](https://user-images.githubusercontent.com/7603237/189206705-05b35d1b-e390-4cd3-b808-e99087ee101c.png)

**Comment by LecCory** [comment]
Removed the hover icon, and placed the password requirements into the form beneath the password fields. Also added visual queues to indicate when a requirement has been met



![Image](https://user-images.githubusercontent.com/17506947/191775941-d2ad338b-4cc4-4b5f-9fe8-fab9c3077319.gif)

**Comment by LecCory** [comment]
@piet0024 As this is a small change to the UI and also the user experience should we have the UI/UX team review before merging the PR? I know I've made visual queues but have I created an additional accessibility issue by using Red/Green color coding?

**Comment by piet0024** [comment]
Yes, I agree I will try and coordinate getting someone from the UX team to review this before we merge. I will also find some time to do a code review.
