### ISSUE TITLE
GCaccount security settings page - update action buttons with more verbose text

### ISSUE THREAD

**Issue by piet0024** [gctools-outilsgc/concierge#225]
Update button text to include more information about the action being performed. 
Ex: "Confirm password reset".
Also look at buttons where more context on the action button is required, this text can be hidden visually with CSS as long as it can continue to be read by assistive technology.

![Image](https://user-images.githubusercontent.com/7603237/189416372-91147656-e144-4c7e-a954-7c9fec8115be.png)

**Comment by doug0102** [comment]
@Chaza-A 
To do:

- Add text for password inputs to tell screen readers "Enter current password", "enter new password", and "enter new password to confirm"
- Change password button from "Confirm" to "Submit new password"
- Add alt text to password button that says "Submit new password button"
- Change security questions button from "Set questions" to "Set security questions"
- Add alt text for 2fa button "Enable two-factor authentication button"
- Change logout buttons on sessions to primary color.
- Change capitalization on GCaccount and GCmessage so it's read correctly by screen readers.
- Add text for screen readers on authorized application items. "Expand box" and "Box expanded".
