### ISSUE TITLE
Fix Docker / npm build

### ISSUE THREAD

**Issue by Phanoix** [gctools-outilsgc/concierge#231]
Docker build is running into npm related errors, dependabot PRs should be a good starting point.

**Comment by doug0102** [comment]
@Phanoix I opened a new branch here https://github.com/gctools-outilsgc/concierge/tree/231

I pushed my changes to the dockerfile that worked on Windows as well as updated the readme letting people know about the CRLF issue.

**Comment by piet0024** [comment]
I was able to build concierge locally on that branch (231). I had to make a change to the Dockerfile here https://github.com/gctools-outilsgc/concierge/blob/231/Dockerfile#L5 I had to change this line to just `npm` and it built.

**Comment by Phanoix** [comment]
@piet0024  yeah, looks like the nodejs package doesn't include npm anymore and it needs to be installed separately now like you said with nodejs-npm.
