### ISSUE TITLE
WIKI: French "Se Connecter" leads to English log in page

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/concierge#31]
## User Story for the issue in the format of "As a user of type AAA, I need XXX so that I can YYY."
As a user whose first language is French, when I click on "Se Connecter" on the French page, I need for the browser to lead me to the French log in page

## Details on issue or enhancement
When "Se Connecter" on the French page is clicked it leads you to the English log in, it would have to be changed to be linked to the French log in page.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
Language should now be shared between GCcollab Account, GCcollab and partially for GCcollab Wiki. Looking into better options for the wiki.
