### ISSUE TITLE
WIKI: On French log in change "Termes et Conditions" to "Conditions d'utilisation" 

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/concierge#32]
## Details on issue or enhancement
Change the "Termes et Conditions" on the French log in page to "Conditions D'Utilisation"

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
Text has been updated to "Conditions D'Utilisation". Merci!

**Comment by LemieuxGen** [comment]
Changes applied - looks great. thanks!
