### ISSUE TITLE
WIKI: Change text from English to French in account settings

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/concierge#33]
## Details on issue or enhancement
On the French version of the Log in account page, change the GCCollab Account to "Compte GCcollab"

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
I imagine this will require some changes to the AppCustomization since we only have a unilingual site title... thoughts @piet0024 @ethanWallace ?

**Comment by ethanWallace** [comment]
Yeah we will need to modify our AppCustomization model to do this. We will need to make a plan on the best way to do this.
