### ISSUE TITLE
WIKI: Change the logo in the account services to the GCTOOLS logo

### ISSUE THREAD

**Issue by sabrinatbs** [gctools-outilsgc/concierge#34]
## Details on issue or enhancement
The logo on the top left of the account services need to be changed to the GCTools logo instead of the GCCollab logo to keep up with consistency.

## For the development team
- [ ] Issue user story documented
- [ ] UX input received
- [ ] Design completed
- [ ] Design validated by business team / UX
- [ ] Code review completed by peer
- [ ] Issue closing comment references any duplicate or connected issues or pull requests
- [ ] Issue closed

**Comment by markwooff** [comment]
Done!
