### ISSUE TITLE
Integrating Freshdesk into single-sign on

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/concierge#45]
We will need to conduct research behind how to integrate Freshdesk into the single account service and what this will look like on the front/backend.

Things to consider: 
- the ticketing process _and_ solutions (help articles)
- separating tickets by platform/'app'. Creating a separate repo/page for each service isn't necessarily sustainable as our suite of services continues to grow. Investigate other alternatives to organize incoming tickets and outgoing help articles
- how this will impact platforms not yet connected to the single sign-on (GCpedia, GCconnex)

@LemieuxGen @cdegrass @KevinChagnon

**Comment by markwooff** [comment]
I believe @KevinChagnon had some preliminary discussions with the FreshDesk folks about being able to integrate our Single Sign-On. It would be amazing to have the same user from our GCcollab Account able to post an issue into FreshDesk without creating _another_ account.

**Comment by klecuyer** [comment]
@markwooff agreed. Right now a lot of these existing account service issues are around confusion with Freshdesk. Unfortunately it's hard to track because we're not going to add another Freshdesk ticket type for 'Freshdesk problems' (haha). 
It just adds another layer of confusion to users. They end up requesting a password from Freshdesk thinking its GCcollab/GCconnex. Or they submit a ticket for help and get an instant reply saying 'Create your Freshdesk account'. No matter how explicit we are in the email, they get very confused and from a UX perspective I totally understand why.

**Comment by marianneaubrey15** [comment]
Workflow @markwooff   ![Workflow Freshdesk (1).jpg](https://zube.io/files/tbs-sct/052d2eab51f1f4c3e2bc869c412e8a35-workflow-freshdesk-1.jpg)

**Comment by markwooff** [comment]
Freshdesk integration has been added as part of the GCcollab Account. Users may now use the same account for Freshdesk as they do for GCcollab/wiki/message.
