### ISSUE TITLE
Add GCcollab Message icon and link to Account Menu

### ISSUE THREAD

**Issue by LemieuxGen** [gctools-outilsgc/concierge#52]
Add GCcollab Message icon and link to the Account menu, along with the icons/links to Wiki and GCcollab. @MPM9000 please add graphic files here. Thanks.

**Comment by MPM9000** [comment]
![mini_message_icon](https://user-images.githubusercontent.com/36711228/39427376-7f3c53c8-4c51-11e8-9799-37db900a89a1.png)
