### ISSUE TITLE
Password complexity requirements go against latest NIST guidance

### ISSUE THREAD

**Issue by nschonni** [gctools-outilsgc/concierge#53]
Awesome stuff with the MFA being added!
I went to change an old weak password after and hit a new password complexity requirement. This goes against the current security guidance from NIST (CSE harmonizes guidance from their specs).
Here is a human readable version of the changes https://venturebeat.com/2017/04/18/new-password-guidelines-say-everything-we-thought-about-passwords-is-wrong/

> No more imposed password complexity (like requiring a combination of letters, numbers, and special characters). This means users now can be less “creative” and avoid passwords like “Password1$”, which only provide a false sense of security.

Moved from https://github.com/gctools-outilsgc/gccollab/issues/306

**Comment by Troy-Lawson** [comment]
coming up with strategy for implementation

**Comment by brucetbarrett** [comment]
TBS follows ITSG-33 not NIST 800-63B. Please check with me before committing any changes.

**Comment by nschonni** [comment]
This was shared the other day from TBS security (from something else) http://intranet.canada.ca/wg-tg/pg-omp-eng.asp
