### ISSUE TITLE
Validation emails sending in Dutch

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/concierge#58]
Currently activation emails for new accounts are sending in English, French, and Dutch.

Please remove Dutch from all outgoing emails.

![image](https://user-images.githubusercontent.com/29754185/39881083-c748c4d6-544d-11e8-9da8-042535db8c46.png)

@bryan-robitaille @piet0024

**Comment by bryan-robitaille** [comment]
Looks like issue is the line in settings.py where all the languages are listed made it into prod:
`LANGUAGES = [
    ('en', _('English')),
    ('nl', _('Dutch')),
    ('fr', _('French'))
]`

**Comment by bryan-robitaille** [comment]
@piet0024 given the work you've done in concierge with the language can you confirm if removing `('nl', _('Dutch'))` from the settings.py will resolve the issue?

**Comment by piet0024** [comment]
Correct https://github.com/gctools-outilsgc/concierge/blob/master/pleio_account/settings.py#L144

Removing dutch from the settings will send the email in just french and english and will change the site language toggle to a button instead of the dropdown.

**Comment by Phanoix** [comment]
New branch and container tag added and deployed with the change discussed above.
