### ISSUE TITLE
Implement Account Lockout functionality

### ISSUE THREAD

**Issue by bryan-robitaille** [gctools-outilsgc/concierge#61]
Complete and implement account lockout functionality.
gctools-outilsgc/concierge#57

**Comment by brucetbarrett** [comment]
As a point of reference, the GoC standard for Protected B systems is to:
- lockout an account after a maximum of 5 failed attempts, and
- lockout the account for a minimum of 5 minutes

This is specified in ITSG-33, Annex 4A, control number AC-7.
A list of all the controls can be found here in [PDF](https://www.cse-cst.gc.ca/en/system/files/pdf_documents/itsg33-ann4a-1-eng_3.pdf) or [Excel](https://www.cse-cst.gc.ca/en/system/files/excel_documents/itsg33-ann4a-eng_3.xls) formats. Warning - big document!

**Comment by amablex** [comment]
1) sprint review:
https://github.com/gctools-outilsgc/ux_prototypes/blob/master/Account/lockout%20functionality/sprint%2042.pdf

2) flowcharts:
https://github.com/gctools-outilsgc/ux_prototypes/blob/master/Account/lockout%20functionality/lockout%20functionality%20flowchart.pdf

3) new screens:
https://github.com/gctools-outilsgc/ux_prototypes/tree/master/Account/lockout%20functionality/Iteration%20%231%20new%20screens

**Comment by bryan-robitaille** [comment]
Update - Jan 10
*The language isn't switching between french and english for the newly added text.  Investigating now - first impressions are that the language files are throwing errors when compiling.

**Comment by TkTech** [comment]
Most of the new text simply isn't being wrapped by `trans` and so is never translated.

**Comment by bryan-robitaille** [comment]
Found issue.  The text is wrapped however the template is not where you would expect to find it.  The issue was that the po files were corrupted and not being compiled to .mo's.  Fixed the duplicates by using GNU gettext utility msguniq.  Compiled po's to mo's and the text now translates properly when language toggle is used.
