### ISSUE TITLE
Move environment variable settings to be set in Django Admin

### ISSUE THREAD

**Issue by bryan-robitaille** [gctools-outilsgc/concierge#62]
Reduce the number of environment variables being set and move the administration of email server settings, profile as a service endpoint, etc to be modified and set in the Django Admin interface.

**Comment by ToferC** [comment]
Of potential use: 

https://github.com/jazzband/django-constance

https://github.com/edx/django-config-models

**Comment by ethanWallace** [comment]
Thanks @ToferC I found this one right before lunch: https://github.com/lazybird/django-solo
But I will take a look at all of these to see which one is best

**Comment by ethanWallace** [comment]
Would someone be able to provide me with a list of the environment variables we would like to transfer into the admin interface? I have a general idea about some of them but I just want an exact list so I don't miss any.

**Comment by Phanoix** [comment]
Having a look at what needs to get set in [the kubernetes yaml](https://github.com/gctools-outilsgc/Kubernetes-config/blob/master/prod/concierge/service.yaml) I'd say the email related parts and maybe the freshdesk / whitelist ones.

**Comment by Phanoix** [comment]
My opinion on what should be where, would be great to get a more general discussion about this:
* version control (settings files / github)
  * Anything required by Concierge regardless of infrastructure, prod/dev, etc.
  * Anything that's useful to have in github with full version control
* environment variables or k8s secrets/configmaps 
  * anything that's actually necessary to get an instance of Concierge running - for example db credentials
  * anything dependent on the environment / infrastructure it's running on ex. dns/host name, https cookie settings
* database (set in Django admin panel) 
  * site - specific variables
  * anything that isn't needed or even counterproductive to or would cause problems when setting up local dev instances, preprod / review instances, etc. ex. email server settings.
