### ISSUE TITLE
R&D into why users create multiple accounts

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/concierge#63]
We want to understand why users create multiple accounts on the system. This issue is for R&D into why users do this. Once we understand why we can develop a strategy to deal with it (separate work item)

**Comment by alex-mes** [comment]
[Why do users have multiple accounts final.pdf](https://zube.io/files/tbs-sct/7ccf6337f161323fb079559172e0e484-why-do-users-have-multiple-accounts-final.pdf)
