### ISSUE TITLE
Users unable to connect to GCcollab Message

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/concierge#78]
Going to use this place to formally document details of users who cannot connect to GCcollab Message.

pierre-louis.gauthier@cra-arc.gc.ca (CRA) cannot access GCcollab Message without getting the 'Connecting' bar loading over and over again. He can login but can't access any channels successfully.

![image](https://user-images.githubusercontent.com/29754185/43790175-d182e1ba-9a3f-11e8-8dc1-e3fc8d888197.png)

![image](https://user-images.githubusercontent.com/29754185/43790166-caa7b10e-9a3f-11e8-8ab5-33203c038e0a.png)

https://gccollab.gctools-outilsgc.ca/helpdesk/tickets/3394

**Comment by klecuyer** [comment]
He did eventually gain access, but after saving 'Highlight words' under My Account in RocketChat he lost access again, just infitely loading dots 'Connecting...'

**Comment by TkTech** [comment]
These are/were issues in the upstream Rocket.Chat, resolved quite awhile ago.
