### ISSUE TITLE
Link between Account and GCcollab Profile

### ISSUE THREAD

**Issue by klecuyer** [gctools-outilsgc/concierge#80]
As an admin, I need to be able to see which profile is attached to which account. Without phpmyadmin I have no way to confirm which profile is attached to which account.

I have seen duplicate accounts and duplicate profiles. I need a link on the user's page in the Account settings to easily direct me to the associated profile in GCcollab.

**Comment by bryan-robitaille** [comment]
This will need to be implemented on the GCcollab side.  Account isn't aware of any profiles and only deals with authentication.  What we can do in Account is make the 'sub' (aka user unique id) displayed on the django admin users page.  That unique identified could then be used in a plugin created for GCcollab to find the profile associated with that ID.
