### ISSUE TITLE
Following installation steps in README does not result in a usable instance.

### ISSUE THREAD

**Issue by TkTech** [gctools-outilsgc/concierge#92]
## Problem

Likely because of PR gctools-outilsgc/concierge#82 creating a new instance from scratch will result in an unusable site due to a missing `SiteConfiguration` record. It must currently be manually created in the database in order to use the instance.

## Solutions

- Document the process of adding a `SiteConfiguration` record and what each setting means.
- [or] add a command to populate it.

## Better Solution

Revert and remove `SiteConfiguration` entirely and instead use one of the many existing django modules for [live settings](https://djangopackages.org/grids/g/live-setting/). These include caching, proper cache invalidation, setting forms (admin integration), help text (i18), support for contrib.sites, etc..

**Comment by bryan-robitaille** [comment]
Known issue.  PR #86 fixes this by updating the readme and resolving the device_id error.  The SiteConfiguration error is in PR #87
