### ISSUE TITLE
determine theme strategy for merged project

### ISSUE THREAD

**Issue by Troy-Lawson** [gctools-outilsgc/concierge#99]
review and figure out what to change

**Comment by ethanWallace** [comment]
Moving forward with the merged project, we decided to create a GC theme for concierge. This way we can meet requirements and needs from our team in terms of brand and FIP without being having to constantly modify the app customization. 

Our hope is to keep the generic app customization theme as the default core theme and allow anyone who downloads the project to easily style account but also the choice to develop a more customized theme if they choose to.
